# Generated by Django 4.0.5 on 2022-06-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('WAIT', 'Waiting'), ('SEND', 'Sending'), ('RCVE', 'RCVE'), ('RJCT', 'RJCT')], default='WAIT', max_length=4)),
                ('username', models.CharField(max_length=255)),
                ('order_date', models.DateTimeField()),
                ('order_total', models.BigIntegerField()),
            ],
        ),
    ]
