# Generated by Django 4.0.5 on 2022-06-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('WAIT', 'WAIT'), ('SEND', 'SEND'), ('RCVE', 'RCVE'), ('RJCT', 'RJCT')], default='WAIT', max_length=4),
        ),
    ]
